config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  as :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :entries
  root "entries#index"
end

app/models/activity.rb
class Activity < ApplicationRecord
    has_many :entries
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
    
        belongs_to :category
        belongs_to :user
        belongs_to :activity
        validates :category_id, presence: true
        validates :activity_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :entries
       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  def index
    if user_signed_in?
      if params[:category]
        @entries = current_user.entries.where( category_id:params[:category]).order(date: :asc)
      else
        @entries = current_user.entries.all.order(date: :asc)
      end
    else
      redirect_to new_user_session_path
    end
  end

  def new
    @entry = current_user.entries.build
  end

  def create
    @entry = current_user.entries.build(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_entry
    @entry = current_user.entries.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:activity_id, :duration, :calories_burned, :category_id, :date, :rep_count, :weight, :distance)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Activity name:</strong>
    <%= entry.activity_name %>
  </p>
  <p>
    <strong>Duration:</strong>
    <%= entry.duration %>mins
  </p>
  <p>
    <strong>Calories burned:</strong>
    <%= entry.calories_burned %>
  </p>
<% if entry.category %>
<p>
<strong>Category:</strong>
<%= entry.category.name %>
</p>
<% else %>
<p>
<strong>Category:</strong>
None
</p>
<% end %>

<% if entry.reps %>
<p>
<strong>Reps:</strong>
<%= entry.reps %>
</p>
<% end %>

<% if entry.weight %>
<p>
<strong>Weight:</strong>
<%= entry.weight %>kg
</p>
<% end %>

<% if entry.distance %>
<p>
<strong>Distance:</strong>
<%= entry.distance %>m
</p>
<% end %>

  <p>
    <strong>Date:</strong>
    <%= entry.date %>
  </p>
</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="message is-danger">
      <div class="message-header">
        <p><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</p>
      </div>

      <div class="message-body">
        <ul>
          <% entry.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :activity_id, style: "display: block", class: "label" %>
<%= form.collection_select :activity_id, Activity.all, :id, :name, { prompt: "Select an activity" }, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :duration, style: "display: block", class: "label"%>
    <%= form.number_field :duration , class: "input"%>
  </div>

  <div class="field">
    <%= form.label :calories_burned, style: "display: block", class: "label" %>
    <%= form.number_field :calories_burned, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :rep_count, style: "display: block", class: "label" %>
    <%= form.number_field :rep_count, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :weight, style: "display: block", class: "label" %>
    <%= form.number_field :weight, class: "input" %>
  </div>

  <div class="field">
    <%= form.label :distance, style: "display: block", class: "label" %>
    <%= form.number_field :distance, class: "input" %>
  </div>
  
  <div class="field">
    <%= form.label :category, style: "display: block", class: "label" %>
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Select a category" }, class: "input" %>
    <%# <%= form.select :category_id, Category.all.collect {|c| [c.name, c.id]} %>

  </div>

  <div class="field">
    <%= form.label :date, style: "display: block", class: "label" %>
    <%= form.datetime_field :date, class: "input" %>
  </div>

  <div class="actions">
  <%= form.submit "Submit", class: "button is-primary is-medium is-fullwidth" %>
</div>
<% end %>

app/views/entries/edit.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">Editing Exercise</h1>
    <%= render "form", entry: @entry %>
  </div>
</div>

app/views/entries/index.html.erb
<% content_for :title do %>
  Move and Groove
<% end %>

<div class="jumbotron has-background-info is-rounded">
  <h1 class="title is-1 has-text-white has-text-centered" style="padding: 1rem;">Get Fit and Groove On</h1>
  <p class="subtitle is-4 has-text-white has-text-centered" style="padding: 1rem;">Your Ultimate Fitness Tracker!</p>
</div>

<div class="columns is-multiline is-centered mt-6">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">
      <div class="card has-margin has-border is-bordered has-rounded-corners is-medium-rounded">
        <header class="card-header">
          <p class="card-header-title"><%= entry.activity.name %></p>
          <div class="card-header-icon">
            <span class="tag is-info is-small"><%= entry.category.name %></span>
          </div>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold">Duration: <%= entry.duration %> mins</span></p>
            <p><span class="has-text-weight-bold">Calories: <%= entry.calories_burned %></span></p>
            <% if entry.created_at > 24.hours.ago %>
              <p><span class="has-text-weight-bold"><%= time_ago_in_words(entry.created_at) %> ago</span></p>
            <% else %>
              <p><span class="has-text-weight-bold">Date: <%= entry.date.strftime("%B %d, %Y") %></span></p>
              <p><span class="has-text-weight-bold">Time: <%= entry.date.strftime("%I:%M %p") %></span></p>
            <% end %>
            <%= link_to 'View', entry_path(entry), class: "button is-info is-small" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/entries/new.html.erb
<div class="columns is-centered mt-6">
  <div class="column is-one-third">
    <h1 class="is-size-2 has-text-weight-bold mb-3">New Exercise</h1>
    <%= render 'form', entry: @entry %>
  </div>
</div>

app/views/entries/show.html.erb
<% content_for :title do %>
  <%= @entry.activity_name %>
<% end %>

<div class="columns mt-6 is-centered">
  <div class="column is-one-quarter">

    <nav class="panel is-black">
      <p class="panel-heading">
        <%= @entry.activity.name %>
      </p>

      <div class="panel-block">
        Duration: <%= @entry.duration %>mins
      </div>

      <div class="panel-block">
        Calories: <%= @entry.calories_burned %>
      </div>

      <div class="panel-block">
        Reps: <%= @entry.rep_count %>
      </div>

      <div class="panel-block">
        Weight: <%= @entry.weight %>kg
      </div>

      <div class="panel-block">
        Distance: <%= @entry.distance %>m
      </div>

      <div class="panel-block">
        Category: <%= @entry.category.name %>
      </div>

      <div class="panel-block">
       <%= time_ago_in_words(@entry.created_at) %> ago
      </div>
    </nav>

   <div class="columns is-mobile">
    <div class="column is-narrow is-inline-block">
      <%= link_to "Edit", edit_entry_path(@entry), class: "button is-success" %>
    </div>
    <div class="column is-narrow is-inline-block">
      <%= link_to "Back", entries_path, class: "button is-link" %>
    </div>
    <div class="column is-narrow is-inline-block">
      <%= button_to "Del", entry_path(@entry), method: :delete, class: "button is-danger", data: { confirm: "Are you sure?" } %>
    </div>
  </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Move and Groove</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>
    
    <% if notice.present? %>
      <div class="notification is-link is-light"> <%= notice %> </div>
    <% end %>

    <% if alert.present? %>
      <div class="notification is-danger is-light"> <%= alert %> </div>
    <% end %>

    <div class="container">
      <%= yield %>
    </div>
    <%= render "shared/footer" %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer has-background-dark">
  <div class="container">
    <div class="columns is-vcentered">
      <div class="column">
        <nav class="level is-mobile">
          <div class="level-item has-text-centered">
            <div>
              <p class="heading"><a href="/" class="has-text-white">Home</a></p>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <div class="navbar-item has-dropdown is-hoverable">
                <a class="navbar-link has-text-white">
                  Categories
                </a>
                <div class="navbar-dropdown has-background-dark">
                  <%= form_tag entries_path, method: :get, class: "select-form" do %>
                    <div class="field has-addons">
                      <div class="control">
                        <%= select_tag :category, options_for_select(Category.all.collect { |c| [c.name, c.id] }), prompt: "Select a category", class: "select is-rounded is-info is-medium" %>
                      </div>
                      <div class="control">
                        <%= submit_tag "Select", class: "button is-info is-rounded is-medium" %>
                      </div>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div class="level-item has-text-centered">
            <div>
              <p class="heading"><a href="/entries/new" class="has-text-white">New Entry</a></p>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <div class="columns">
      <div class="column">
        <p class="has-text-centered has-text-white">Copyright © 2023
          Move and Groove
        </p>
      </div>
    </div>
  </div>
</footer>

<style>
 html {
  position: relative;
  min-height: 100%;
}

footer {
  position: absolute;
  bottom: -150px;
  width: 100%;
  height: 100px;
  margin-top: 150px; /* change this value to be greater than 100px */
}
</style>

app/views/shared/_header.html.erb
<nav class="navbar is-spaced is-dark is-double_height" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <a class="navbar-item is-large" href="/">
      <%= image_tag "Fitness_Tracker_logo.png", alt: "Image description", class: "is-size-2 p-0" %>
    </a>

    <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
      <a class="navbar-item" href="/">
        Home
      </a>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Categories
        </a>

        <div class="navbar-dropdown has-background-dark">
          <%= form_tag entries_path, method: :get, class: "select-form" do %>
            <div class="field has-addons">
              <div class="control">
                <%= select_tag :category, options_for_select(Category.all.collect { |c| [c.name, c.id] }), prompt: "Select a category", class: "select is-rounded is-info is-medium" %>
              </div>
              <div class="control">
                <%= submit_tag "Select", class: "button is-info is-rounded is-medium" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    
    <h1 class="navbar-item has-text-light is-size-2 has-text-centered has-text-weight-bold">Move and Groove</h1>


    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
            <a class="button is-primary" href="/entries/new">
              New
            </a>
        </div>
      </div>
      <div class="navbar-item">
        <div class="buttons">
          <% if user_signed_in? %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "button is-primary" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "button is-primary" %>
            <%= link_to "Register", new_user_registration_path, class: "button is-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>